#baseurl = "https://example.org"
#baseurl = "https://gorda.io/"
baseurl = "https://gorda.github.io/"
title = "Gorda"

theme = "less"
languageCode = "zh-CN"
defaultContentLanguage = "zh-CN"
hasCJKLanguage = true
preserveTaxonomyNames = true
paginate = 10
paginatePath = "page"


enableRobotsTXT = false
googleAnalytics = ""
disqusShortname = ""

[taxonomies]
  tag = "tags"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "主页"
    weight = 1
    url = "/"
#[[menu.main]]
#    name = "归档"
#    weight = 2
#    url = "/archive/"
[[menu.main]]
    name = "Tag"
    weight = 3
    url = "/tags/"
[[menu.main]]
    name = "实验室"
    weight = 4
    url = "/labs/"
[[menu.main]]
    name = "关于我"
    weight = 5
    url = "/about/"

[params]
    mainSections = ["post"]
    description = ""
    static = "https://static.sguan.top/"
    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Gorda logo"

    [params.icon]
    url = "favicon.ico"
