name: CI
on:
  push:
    branches:
      - master2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.5
        with:
          hugo-version: '0.65.3'
          extended: true

      - name: Build for github.io
        run: hugo --minify --baseURL https://gorda.github.io/

      - name: Deploy to github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: gorda/gorda.github.io
          publish_branch: master
          publish_dir: ./public

      - name: Build for gorda.io
        run: hugo --minify --baseURL https://gorda.io/

      - name: Deploy to gorda.io
        env:
          ID_RSA: ${{ secrets.ID_RSA }}
          DO_HOST: ${{ secrets.DO_HOST }}
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "$ID_RSA" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          mv ./public ./www
          scp -o StrictHostKeyChecking=no -r ./www $DO_HOST