name: Action
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Hexo Clean
        uses: heowc/action-hexo@master
        with:
          args: clean

      - name: Load and Generate for 3ks.github.io
        env:
          HY: ${{ secrets.HEXO_YAML }}
          HPT: ${{ secrets.HEXO_POST_YAML }}
          HGY: ${{ secrets.HEXO_GITHUB_YAML }}
        run: |
          rm -f ./themes/icarus/_config.yml
          sudo echo "${HY}" > ./themes/icarus/_config.yml
          sudo echo "${HPT}" > ./themes/icarus/_config.post.yml
          sudo echo "${HGY}" > _config.yml

      - name: Hexo Generate for 3ks.github.io
        uses: heowc/action-hexo@master
        with:
          args: generate

      - name: Deploy to 3ks.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: 3ks/3ks.github.io
          publish_branch: master
          publish_dir: ./public

      - name: Load and Generate for 3ks.dev
        env:
          HSY: ${{ secrets.HEXO_SITE_YAML }}
        run: |
          sudo echo "${HSY}" > _config.yml

      - name: Hexo Generate for 3ks.dev
        uses: heowc/action-hexo@master
        with:
          args: generate

      - name: Deploy to 3ks.dev
        env:
          ID_RSA: ${{ secrets.ID_RSA }}
          DO_HOST: ${{ secrets.DO_HOST }}
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "$ID_RSA" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          mv ./public ./3ks
          scp -o StrictHostKeyChecking=no -r ./3ks $DO_HOST